---

- name: update
  hosts: devops
  become: yes
  tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
    - name: Upgrade Packages
      apt: 
        name: "*"
        state: latest
    - name: Clean Packages
      apt:
        autoremove: yes